default: &default
  adapter: postgresql
  encoding: unicode
  username: gcelanji
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: connected_development

test:
  <<: *default
  database: connected_test

# production:
#   <<: *default
#   database: your_app_production
#   username: your_prod_user
#   password: <%= ENV['PROD_DB_PASSWORD'] %>
